save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  start_location: "$.message.intent.fulfillment.stops[?(@.type=='START')].location.gps"
  end_location: "$.message.intent.fulfillment.stops[?(@.type=='END')].location.gps"
  
  collected_by: "$.message.intent.payment.collected_by" 
  search_1_fulfillment: "$.message.intent.fulfillment"
  stops: "$.message.intent.fulfillment.stops[*]"
  vehicle_category: "$.message.intent.fulfillment.vehicle.category" 
  search_1_tags: "$.message.intent.tags"
  search_1_descriptor_code: "$.message.intent.category.descriptor.code"
  search_1_intent_category: "$.message.intent.category"
  search_vehicle_category: "$.message.intent.fulfillment.vehicle.category"
  search_1_items: "$.message.intent.provider.items[*]"
  search_1_payment: "$.message.intent.payment"