catalog:
  descriptor:
    name: ABC Insurance Ltd
  providers:
    - categories:
        - descriptor:
            name: Micro Insurance
            code: MICRO_INSURANCE
          id: C1
        - descriptor:
            name: Micro Accidental Insurance
            code: MICRO_ACCIDENTAL_INSURANCE
          parent_category_id: C1
          id: C2
      descriptor:
        long_desc: ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc
        name: ABC Insurance Ltd.
        short_desc: ABC Insurance Ltd. India
        images:
          - url: https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png
            size_type: xs
      id: P1
      tags:
        - descriptor:
            code: MASTER_POLICY
          list:
            - descriptor:
                code: POLICY_ID
              value: e103b4a5-10f8-42c7-b888-dbf0e2edd696
      items:
        - id: I1
          category_ids:
            - C2
          descriptor:
            name: Micro Accidental Insurance
            short_desc: ABC Individual Insurance Class
          time:
            duration: P1Y
            label: TENURE
          tags:
            - descriptor:
                code: BAP_INPUTS
              list:
                - descriptor:
                    code: BUYER_NAME
                    short_desc: "Describes the format as  'Salutation | First Name | Middle Name | Last Name' represents a full name structure, where the values are separated by a pipe (|) symbol"
                  value: "-"
                - descriptor:
                    code: BUYER_PHONE_NUMBER
                    short_desc: "Describes the format as: the first two characters represent the country code, followed by a 10-digit mobile number, separated by a hyphen (-)."
                  value: "-"
                - descriptor:
                    code: BUYER_DOB
                    short_desc: "Describes the format as: DD/MM/YYYY, separated by a forward slash ( / )."
                  value: "-"
                - descriptor:
                    code: BUYER_PAN_NUMBER
                    short_desc: "Describes the PAN number in alphanumeric format"
                  value: "-"
                - descriptor:
                    code: BUYER_PED
                    short_desc: "Describes the PED details, which can be set to either true or false."
                  value: "-"
                - descriptor:
                    code: SUM_INSURED
                    short_desc: "Describes the format as: a numerical value without separators"
                  value: "-"
                - descriptor:
                    code: BUYER_EMAIL
                  value: "-"
                - descriptor:
                    code: TENURE
                    short_desc: "Describes the tenure in ISO 8601 duration format like P6M = 6 months &  P1Y = 1 year etc."
                  value: "-"
                - descriptor:
                    code: TENURE_TYPE
                  value: "-"
      payments:
        - collected_by: BPP
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bpp.com/booking/terms
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
