save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
  items: "$.message.catalog.providers[*].items[*]"
  provider_id: "$.message.catalog.providers[0].id"
  item: "$.message.catalog.providers[0].items[0]"
  fulfillments: "$.message.catalog.fulfillments[*]"
  selected_provider: "$.message.catalog.providers[0]"