catalog:
  descriptor:
    name: ABC Bus Services Solutions
    images:
      - url: https://abc-bus.in/logos/logo.ico
  providers:
    - id: P1
      descriptor:
        name: ABC Operator 1 Bus Services
        images:
          - url: https://operator1.com/logos/logo.ico
      fulfillments:
        - id: F1
          type: TRIP
          stops:
            - type: START
              location:
                descriptor:
                  name: Bangalore
                  code: std:080
                gps: "12.979759, 77.590427"
            - type: PICKUP
              location:
                descriptor:
                  name: Agara
                  code: std:080-pincode:560034
                gps: "12.924479, 77.648999"
            - type: PICKUP
              location:
                descriptor:
                  name: Bellandur
                  code: std:080-pincode:560103
                gps: "12.930839, 77.677941"
            - type: END
              location:
                descriptor:
                  name: Hyderabad
                  code: std:040
                gps: "17.399832, 78.505532"
            - type: DROP
              location:
                descriptor:
                  name: Ameerpet
                  code: std:040-pincode:500016
                gps: "17.441586, 78.441581"
            - type: DROP
              location:
                descriptor:
                  name: Central Bus Station
                  code: std:040-pincode:500012
                gps: "17.379024, 78.482443"
          vehicle:
            category: BUS
            variant: AC
            capacity: 47
            wheels_count: "6"
            energy_type: DIESEL
        - id: F2
          type: TRIP
          stops:
            - type: START
              location:
                descriptor:
                  name: Bangalore
                  code: std:080
                gps: "12.979759, 77.590427"
            - type: PICKUP
              location:
                descriptor:
                  name: Agara
                  code: std:080-pincode:560034
                gps: "12.924479, 77.648999"
            - type: PICKUP
              location:
                descriptor:
                  name: Bellandur
                  code: std:080-pincode:560103
                gps: "12.930839, 77.677941"
            - type: END
              location:
                descriptor:
                  name: CHENNAI
                  code: std:040
                gps: "17.399832, 78.505532"
            - type: DROP
              location:
                descriptor:
                  name: Ameerpet
                  code: std:040-pincode:500016
                gps: "17.441586, 78.441581"
            - type: DROP
              location:
                descriptor:
                  name: Central Bus Station
                  code: std:040-pincode:500012
                gps: "17.379024, 78.482443"
          vehicle:
            category: BUS
            variant: NON-AC
            capacity: 47
            wheels_count: "6"
            energy_type: ELECTRIC
      payments:
        - collected_by: BPP
          tags:
            - descriptor:
                code: BUYER_FINDER_FEES
              display: false
              list:
                - descriptor:
                    code: BUYER_FINDER_FEES_PERCENTAGE
                  value: "1"
                - descriptor:
                    code: BUYER_FINDER_FEES_TYPE
                  value: percent
            - descriptor:
                code: SETTLEMENT_TERMS
              display: false
              list:
                - descriptor:
                    code: SETTLEMENT_WINDOW
                  value: P30D
                - descriptor:
                    code: SETTLEMENT_BASIS
                  value: INVOICE_RECEIPT
                - descriptor:
                    code: MANDATORY_ARBITRATION
                  value: "TRUE"
                - descriptor:
                    code: COURT_JURISDICTION
                  value: New Delhi
                - descriptor:
                    code: STATIC_TERMS
                  value: https://api.transit-solutions.com/booking/terms
