order:
  provider:
    id: P1
  items:
    - id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 3
      category_ids: [C1]
      fulfillment_ids: [F1]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I1-1
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_1]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A1
          descriptor:
            name: meals
            code: MEALS
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "300"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I1-2
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_2]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A2
          descriptor:
            name: Delayed and Lost Baggage Protection
            code: BAGGAGE
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "500"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I1-3
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_3]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I2
      descriptor:
        name: Child
        code: CHILD_TICKET
      price:
        currency: INR
        value: "4280"
      quantity:
        selected:
          count: 2
      category_ids: [C1]
      fulfillment_ids: [F1]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I2-1
      descriptor:
        name: Child
        code: CHILD_TICKET
      price:
        currency: INR
        value: "4280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_4]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A1
          descriptor:
            name: meals
            code: MEALS
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "300"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I2-2
      descriptor:
        name: Child
        code: CHILD_TICKET
      price:
        currency: INR
        value: "4280"
      quantity:
        selected:
          count: 2
      category_ids: [C1]
      fulfillment_ids: [F1, FT_5]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

  fulfillments:
    - id: F1
      type: TRIP
      stops:
        - id: S1
          type: START
          location:
            descriptor:
              name: Delhi
              code: DEL
          time:
            label: DATE_TIME
            timestamp: "2023-10-15T20:00:00.000Z"
        - id: S2
          type: END
          location:
            descriptor:
              name: Bengaluru
              code: BLR
          time:
            label: DATE_TIME
            timestamp: "2023-10-15T20:00:00.000Z"
      vehicle:
        category: AIRLINE
        code: "6E284"
      tags:
        - descriptor: { code: VEHICLE_GRID }
          display: false
          list:
            - descriptor: { code: X_MAX }
              value: "14"
            - descriptor: { code: Y_MAX }
              value: "3"
            - descriptor: { code: Z_MAX }
              value: "1"
            - descriptor: { code: X_LOBBY_START }
              value: "0"
            - descriptor: { code: X_LOBBY_SIZE }
              value: "12"
            - descriptor: { code: Y_LOBBY_START }
              value: "1"
            - descriptor: { code: Y_LOBBY_SIZE }
              value: "1"
            - descriptor: { code: SEAT_SELECTION }
              value: mandatory
        - descriptor: { code: VEHICLE_AVAIBALITY }
          display: false
          list:
            - descriptor: { code: AVALIABLE_SEATS }
              value: "20"
        - descriptor:
            code: INFO
            name: Info
          display: true
          list:
            - descriptor: { code: OPERATED_BY }
              value: AirIndia

    - id: FT_1
      type: TICKET
      tags:
        - descriptor: { code: SEAT_GRID }
          list:
            - descriptor: { code: X }
              value: "0"
            - descriptor: { code: Y }
              value: "0"
            - descriptor: { code: Z }
              value: "0"
            - descriptor: { code: SEAT_NUMBER }
              value: A1
            - descriptor: { code: AVAILABLE }
              value: "true"
            - descriptor: { code: SEAT_PRICE }
              value: "200"

    - id: FT_2
      type: TICKET
      tags:
        - descriptor: { code: SEAT_GRID }
          list:
            - descriptor: { code: X }
              value: "0"
            - descriptor: { code: Y }
              value: "0"
            - descriptor: { code: Z }
              value: "0"
            - descriptor: { code: SEAT_NUMBER }
              value: A2
            - descriptor: { code: AVAILABLE }
              value: "true"
            - descriptor: { code: SEAT_PRICE }
              value: "200"

    - id: FT_3
      type: TICKET
      tags:
        - descriptor: { code: SEAT_GRID }
          list:
            - descriptor: { code: X }
              value: "0"
            - descriptor: { code: Y }
              value: "0"
            - descriptor: { code: Z }
              value: "0"
            - descriptor: { code: SEAT_NUMBER }
              value: A3
            - descriptor: { code: AVAILABLE }
              value: "true"
            - descriptor: { code: SEAT_PRICE }
              value: "200"

    - id: FT_4
      type: TICKET
      tags:
        - descriptor: { code: SEAT_GRID }
          list:
            - descriptor: { code: X }
              value: "0"
            - descriptor: { code: Y }
              value: "0"
            - descriptor: { code: Z }
              value: "0"
            - descriptor: { code: SEAT_NUMBER }
              value: B1
            - descriptor: { code: AVAILABLE }
              value: "true"
            - descriptor: { code: SEAT_PRICE }
              value: "200"

    - id: FT_5
      type: TICKET
      tags:
        - descriptor: { code: SEAT_GRID }
          list:
            - descriptor: { code: X }
              value: "0"
            - descriptor: { code: Y }
              value: "0"
            - descriptor: { code: Z }
              value: "0"
            - descriptor: { code: SEAT_NUMBER }
              value: B2
            - descriptor: { code: AVAILABLE }
              value: "true"
            - descriptor: { code: SEAT_PRICE }
              value: "200"
