message:
  order:
    items:
      - id: I1
        quantity:
          selected:
            count: 2
    provider:
      id: P1
    billing:
      name: John Doe
      email: john.doe@example.com
      phone: +91-9897867564
    payments:
      - id: PA1
        collected_by: BAP
        status: PAID
        type: PRE-ORDER
        params:
          transaction_id: 34cc9b0b-6887-4c63-8397-2f4fcf03e50d
          currency: INR
          amount: "120"
        tags:
          - descriptor:
              code: BUYER_FINDER_FEES
            display: false
            list:
              - descriptor:
                  code: BUYER_FINDER_FEES_PERCENTAGE
                value: "1"
          - descriptor:
              code: SETTLEMENT_TERMS
            display: false
            list:
              - descriptor:
                  code: SETTLEMENT_WINDOW
                value: PT60M
              - descriptor:
                  code: SETTLEMENT_BASIS
                value: Delivery
              - descriptor:
                  code: SETTLEMENT_TYPE
                value: NEFT
              - descriptor:
                  code: MANDATORY_ARBITRATION
                value: "true"
              - descriptor:
                  code: COURT_JURISDICTION
                value: New Delhi
              - descriptor:
                  code: DELAY_INTEREST
                value: "2.5"
              - descriptor:
                  code: STATIC_TERMS
                value: https://www.abc.com/settlement-terms/
              - descriptor:
                  code: SETTLEMENT_AMOUNT
                value: "59"
