codes:
  - code: 200
    action_id: search
    action: search
    default: FIS12/2.0.2/search/default.yaml
    message_id: true
  - code: 201
    action_id: on_search
    action: on_search
    default: FIS12/2.0.2/on_search/default.yaml
    message_id: false
  - code: 202
    action_id: select
    action: select
    default: FIS12/2.0.2/select/default.yaml
    message_id: true
  - code: 2021
    action_id: select_1
    action: select
    default: FIS12/2.0.2/select_1/default.yaml
    message_id: true
  - code: 2022
    action_id: select_2
    action: select
    default: FIS12/2.0.2/select_2/default.yaml
    message_id: true
  - code: 203
    action_id: on_select
    action: on_select
    default: FIS12/2.0.2/on_select/default.yaml
    message_id: false
  - code: 2031
    action_id: on_select_1
    action: on_select
    default: FIS12/2.0.2/on_select_1/default.yaml
    message_id: false
  - code: 2032
    action_id: on_select_2
    action: on_select
    default: FIS12/2.0.2/on_select_2/default.yaml
    message_id: false
  - code: 204
    action_id: init
    action: init
    default: FIS12/2.0.2/init/default.yaml
    message_id: true
  - code: 205
    action_id: on_init
    action: on_init
    default: FIS12/2.0.2/on_init/default.yaml
    message_id: false
  - code: 206
    action_id: confirm
    action: confirm
    default: FIS12/2.0.2/confirm/default.yaml
    message_id: true
  - code: 207
    action_id: on_confirm
    action: on_confirm
    default: FIS12/2.0.2/on_confirm/default.yaml
    message_id: false
  - code: 208
    action_id: update
    action: update
    default: FIS12/2.0.2/update/default.yaml
    message_id: true
  - code: 209
    action_id: on_update
    action: on_update
    default: FIS12/2.0.2/on_update/default.yaml
    message_id: false 
  - code: 210
    action_id: on_update_unsolicited
    action: on_update
    default: FIS12/2.0.2/on_update_unsolicited/default.yaml
    message_id: true
  - code: 211
    action_id: status
    action: status
    default: FIS12/2.0.2/status/default.yaml
    message_id: true
  - code: 212
    action_id: on_status
    action: on_status
    default: FIS12/2.0.2/on_status/default.yaml
    message_id: false
  - code: 213
    action_id: on_status_unsolicited
    action: on_status
    default: FIS12/2.0.2/on_status_unsolicited/default.yaml
    message_id: true