save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  collected_by: "$.message.intent.payment.collected_by" 
  provider_id: "$.message.intent.provider.id" 
  tags: "$.message.intent.provider.tags[*]" 
  city_code: "$.context.location.city.code"
  user_tags: "$.message.intent.provider.items[*].tags[*]"
