codes:
  - code: 200
    action_id: search
    action: search
    default: FIS10/2.1.0/search/default.yaml
    message_id: true
  - code: 201
    action_id: on_search
    action: on_search
    default: FIS10/2.1.0/on_search/default.yaml
    message_id: false
  - code: 202
    action_id: select
    action: select
    default: FIS10/2.1.0/select/default.yaml
    message_id: true
  - code: 203
    action_id: on_select
    action: on_select
    default: FIS10/2.1.0/on_select/default.yaml
    message_id: false
  - code: 204
    action_id: init
    action: init
    default: FIS10/2.1.0/init/default.yaml
    message_id: true
  - code: 205
    action_id: on_init
    action: on_init
    default: FIS10/2.1.0/on_init/default.yaml
    message_id: false
  - code: 206
    action_id: confirm
    action: confirm
    default: FIS10/2.1.0/confirm/default.yaml
    message_id: true
  - code: 207
    action_id: on_confirm
    action: on_confirm
    default: FIS10/2.1.0/on_confirm/default.yaml
    message_id: false
  - code: 208
    action_id: on_status_update_receiver_info
    action: on_status
    default: FIS10/2.1.0/on_status_update_receiver_info/default.yaml
    message_id: true       
  - code: 209
    action_id: status
    action: status
    default: FIS10/2.1.0/status/default.yaml
    message_id: true
  - code: 210
    action_id: on_status
    action: on_status
    default: FIS10/2.1.0/on_status/default.yaml
    message_id: true       
  - code: 211
    action_id: update
    action: update
    default: FIS10/2.1.0/update/default.yaml
    message_id: true
  - code: 212
    action_id: on_update
    action: on_update
    default: FIS10/2.1.0/on_update/default.yaml
    message_id: false
  - code: 213
    action_id: on_cancel
    action: on_cancel
    default: FIS10/2.1.0/on_cancel/default.yaml
    message_id: true 
