order:
  id: POLICY_ID
  status: ACTIVE

  items:
    - id: CHILD_ITEM_ID_I1
      parent_item_id: I1
      category_ids:
        - C2
      descriptor:
        name: Micro Accidental Insurance Plan
        short_desc: Individual Insurance Class
      price:
        currency: INR
        value: "900"
      tags:
        - descriptor:
            name: General Information
            code: GENERAL_INFO
          list:
            - descriptor:
                code: ACCIDENTAL_DEATH_SUM_INSURED
              value: "10000000"
            - descriptor:
                code: PERMANENT_TOTAL_DISABILITY_SUM_INSURED
              value: "10000000"
            - descriptor:
                code: PERMANENT_PARTIAL_DISABILITY_SUM_INSURED
              value: "10000000"
            - descriptor:
                code: TEMPORARY_TOTAL_DISABILITY_SUM_INSURED
              value: "10000000"
            - descriptor:
                code: MEDICAL_EXPENSES_COVERAGE
              value: "100000"
            - descriptor:
                code: HOSPITALIZATION_BENEFITS
              value: "10000"
            - descriptor:
                code: EMI_DURING_TEMPORARY_DISABILITY
              value: "true"
            - descriptor:
                code: EMI_DURING_PERMANENT_DISABILITY
              value: "false"
            - descriptor:
                code: NUMBER_OF_EMI_PAYABLE
              value: "5"
            - descriptor:
                code: INITIAL_WAITING_PERIOD
              value: "true"
            - descriptor:
                code: MINIMUM_AGE_LIMIT
              value: "15"
            - descriptor:
                code: MAXIMUM_AGE_LIMIT
              value: "75"
            - descriptor:
                code: TNC_LINK
              value: "https://fis.test.bpp.io/tnc.html"
            - descriptor:
                code: TENURE_TYPE
              value: TRANSIT
        - descriptor:
            name: Inclusions
            code: INCLUSIONS
          list:
            - descriptor:
                name: Hospitalization
            - descriptor:
                name: Surgery
        - descriptor:
            name: Exclusions
            code: EXCLUSIONS
          list:
            - descriptor:
                name: Physiotherapy
        - descriptor:
            name: Policy Info
            code: POLICY_INFO
          list:
            - descriptor:
                name: Policy Start Date
                code: POLICY_START_DATE
              value: "24/07/2025"
            - descriptor:
                name: Policy End Date
                code: POLICY_END_DATE
              value: "24/07/2026"
            - descriptor:
                name: Policy Renewal Date
                code: POLICY_RENEWAL_DATE
              value: "23/07/2025"
            - descriptor:
                name: Claims Helpdesk - Contact Number
                code: CLAIMS_HELPDESK_CONTACT_NUMBER
              value: "1860 266 7766"
            - descriptor:
                name: Claims Helpdesk - Email ID
                code: CLAIMS_HELPDESK_EMAIL_ID
              value: "helpdesk@fistestbpp.com"
      time:
        duration: P1Y
        label: TENURE

  fulfillments:
    - id: F1
      type: POLICY
      state:
        descriptor:
          code: GRANTED
      customer:
        person:
          name: "Mr. | Joe | Wick | Adams"
          dob: "2001-12-17"
        contact:
          phone: "+91-9988776655"
          email: john.doe@example.com

  provider:
    id: P1
    descriptor:
      name: ABC Insurance Ltd.
      short_desc: ABC Insurance Ltd. India
      long_desc: ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc
      images:
        - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
          size_type: xs
    tags:
      - descriptor:
          code: MASTER_POLICY
        list:
          - descriptor:
              code: POLICY_ID
            value: e103b4a5-10f8-42c7-b888-dbf0e2edd696

  quote:
    id: OFFER_ID/PROPOSAL_ID
    price:
      currency: INR
      value: "1000"
    breakup:
      - title: BASE_PRICE
        price:
          value: "900"
          currency: INR
      - title: CONVIENCE_FEE
        price:
          value: "50"
          currency: INR
      - title: TAX
        price:
          value: "40"
          currency: INR
      - title: PROCESSING_FEE
        price:
          value: "10"
          currency: INR

  payments:
    - id: PA1
      collected_by: BPP
      status: PAID
      type: ON_ORDER
      params:
        amount: "1000"
        currency: INR
        transaction_id: c24dda6f-20e5-4de2-8ca3-f5421a028bff

  cancellation_terms:
    - external_ref:
        mimetype: "text/html,"
        url: "https://fis.test.bpp.io/cancellation-terms"

  documents:
    - descriptor:
        code: POLICY_DOC
        name: Insurance Policy Document
        short_desc: Download your digitally signed policy document here
        long_desc: "Download you digitally signed policy document here. This document is password protected. To open this document, please type in your password in DDMMMYYYYXXXX format where DDMMMYYYY represents your date of birth, and XXXX represents the first four letters of your name"
      mime_type: application/pdf
      url: "https://fis.test.bpp/policies/O1.pdf"

  created_at: "2025-07-24T05:39:40.104Z"
  updated_at: "2025-07-24T05:39:40.104Z"

  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: "https://api.example-bap.com/booking/terms"
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: "https://api.example-bpp.com/booking/terms"
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
