save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  order_id: "$.message.order.id"
  init_items: "$.message.order.id"
  fulfillments: "$.message.order.fulfillments[*]"
  payments: "$.message.order.payments[*]"
  

  