order:
  provider:
    id: P1
    descriptor:
      name: ABC Operator Fights Services
      images:
        - url: https://operator1.com/logos/logo.ico
          size_type: xs
  items:
    - id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 3
      category_ids:
        - C1
      fulfillment_ids:
        - F1
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items
    - id: I1-1
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids:
        - C1
      fulfillment_ids:
        - F1
        - FT_1
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A1
          descriptor:
            name: meals
            code: MEALS
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "300"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: 7 KG
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: 15 KG
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items
    # ... repeat similar structure for I1-2, I1-3, I2, I2-1, I2-2 ...
  fulfillments:
    - id: F1
      type: TRIP
      stops:
        - id: S1
          type: START
          location:
            descriptor:
              name: Delhi
              code: DEL
          time:
            label: DATE_TIME
            timestamp: "2023-10-15T20:00:00.000Z"
        - id: S2
          type: END
          location:
            descriptor:
              name: Bengaluru
              code: BLR
          time:
            label: DATE_TIME
            timestamp: "2023-10-15T20:00:00.000Z"
      vehicle:
        category: AIRLINE
        code: "6E284"
      tags:
        - descriptor:
            code: INFO
            name: Info
          display: true
          list:
            - descriptor: { code: OPERATED_BY }
              value: AirIndia
    # ... repeat for FT_1, FT_2, FT_3, FT_4, FT_5 ...
  quote:
    id: Q1
    price:
      value: "42159"
      currency: INR
    breakup:
      - title: BASE_FARE
        item:
          id: I1
          quantity:
            selected:
              count: 3
          price:
            currency: INR
            value: "9280"
        price:
          currency: INR
          value: "27840"
      - title: BASE_FARE
        item:
          id: I2-1
        price:
          value: "4280"
          currency: INR
      # ... repeat all other breakup entries (TAX, SEAT_FARE, ADD_ONS, OTHER_CHARGES) ...
  payments:
    - id: PA1
      collected_by: BAP
      status: NOT-PAID
      type: PRE-ORDER
      params:
        amount: "42159"
        currency: INR
        bank_code: XXXXXXXX
        bank_account_number: xxxxxxxxxxxxxx
        virtual_payment_address: 9988199772@okicic
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor: { code: SETTLEMENT_WINDOW }
              value: PT30D
            - descriptor: { code: SETTLEMENT_BASIS }
              value: INVOICE_RECEIPT
            - descriptor: { code: MANDATORY_ARBITRATION }
              value: "TRUE"
            - descriptor: { code: COURT_JURISDICTION }
              value: New Delhi
            - descriptor: { code: STATIC_TERMS }
              value: https://api.example-bpp.com/booking/terms
            - descriptor: { code: SETTLEMENT_AMOUNT }
              value: "10421"
  cancellation_terms:
    - cancel_by:
        duration: PT60M
      cancellation_fee:
        percentage: "0"
  billing:
    name: Joe Adams
    phone: "+91-9988776655"
    tax_id: GSTIN:22AAAAA0000A1Z5
