order:
  items:
    - id: I1
      quantity:
        selected:
          count: 2
  fulfillments:
    - id: F1
      stops:
        - id: S2
          type: PICKUP
        - id: S5
          type: DROP
    - id: FT1
      customer:
        person:
          name: Joe Adams
          age: "30"
          gender: MALE
        contact:
          phone: "+91-9988776655"
      tags:
        - descriptor:
            code: SEAT_GRID
          list:
            - descriptor:
                code: NUMBER
              value: A1
    - id: FT2
      customer:
        person:
          name: RACHEL ADAMS
          age: "27"
          gender: FEMALE
        contact:
          phone: "+91-9723797890"
      tags:
        - descriptor:
            code: SEAT_GRID
          list:
            - descriptor:
                code: NUMBER
              value: F1
  provider:
    id: P1
  billing:
    name: Joe Adams
    phone: "+91-9988776655"
    tax_id: GSTIN:22AAAAA0000A1Z5
  payments:
    - id: PA1
      collected_by: BAP
      status: NOT-PAID
      type: PRE-ORDER
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: SETTLEMENT_WINDOW
              value: PT60M
            - descriptor:
                code: SETTLEMENT_BASIS
              value: Delivery
            - descriptor:
                code: SETTLEMENT_TYPE
              value: upi
            - descriptor:
                code: MANDATORY_ARBITRATION
              value: "true"
            - descriptor:
                code: COURT_JURISDICTION
              value: New Delhi
            - descriptor:
                code: DELAY_INTEREST
              value: "2.5"
            - descriptor:
                code: STATIC_TERMS
              value: https://www.abc.com/settlement-terms/
            - descriptor:
                code: SETTLEMENT_AMOUNT
              value: "1766"
