save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  city_code: "$.context.location.city.code"
  order_id: "$.message.order.id"
  order_status: "$.message.order.status"
  items: "$.message.order.items[*]"
  provider: "$.message.order.provider"
  fulfillments: "$.message.order.fulfillments[*]"
  cancellation_terms: "$.message.order.cancellation_terms[*]"
  quote: "$.message.order.quote"
  payments: "$.message.order.payments[*]"
  created_at: "$.message.order.created_at"
  updated_at: "$.message.order.updated_at"
