codes:
  - code: 100
    action_id: search_1_Airline_200
    action: search
    default: Airline/2.0.0/search/search_1/default.yaml
    message_id: true
  - code: 101
    action_id: on_search_1_Airline_200
    action: on_search
    default: Airline/2.0.0/on_search/on_search_1/default.yaml
    message_id: false
  - code: 102
    action_id: on_search_2_Airline_200
    action: on_search
    default: Airline/2.0.0/on_search/on_search_2/default.yaml
    message_id: true
  - code: 103
    action_id: on_search_3_Airline_200
    action: on_search
    default: Airline/2.0.0/on_search/on_search_3/default.yaml
    message_id: true
  - code: 104
    action_id: on_search_4_Airline_200
    action: on_search
    default: Airline/2.0.0/on_search/on_search_4/default.yaml
    message_id: true
  - code: 105
    action_id: select_1_Airline_200
    action: select
    default: Airline/2.0.0/select/select_1/default.yaml
    message_id: true
  - code: 106
    action_id: on_select_1_Airline_200
    action: on_select
    default: Airline/2.0.0/on_select/on_select_1/default.yaml
    message_id: false
  - code: 107
    action_id: select_2_Airline_200
    action: select
    default: Airline/2.0.0/select/select_2/default.yaml
    message_id: true
  - code: 108
    action_id: on_select_2_Airline_200
    action: on_select
    default: Airline/2.0.0/on_select/on_select_2/default.yaml
    message_id: false
  - code: 109
    action_id: init_Airline_200
    action: init
    default: Airline/2.0.0/init/default.yaml
    message_id: true
  - code: 110
    action_id: on_init_Airline_200
    action: on_init
    default: Airline/2.0.0/on_init/default.yaml
    message_id: false
  - code: 111
    action_id: confirm_Airline_200
    action: confirm
    default: Airline/2.0.0/confirm/default.yaml
    message_id: true
  - code: 112
    action_id: on_confirm_Airline_200
    action: on_confirm
    default: Airline/2.0.0/on_confirm/default.yaml
    message_id: false
  - code: 113
    action_id: cancel_Airline_200
    action: cancel
    default: Airline/2.0.0/cancel/default.yaml
    message_id: true
  - code: 114
    action_id: on_cancel_Airline_200
    action: on_cancel
    default: Airline/2.0.0/on_cancel/default.yaml
    message_id: false

  # ---------------------------------INTERCITY---------------------------------
  
  - code: 115
    action_id: search_BUS_201
    action: search
    default: Intercity/2.0.0/search/search_station_code_1/default.yaml
    message_id: true
  - code: 116
    action_id: search_BUS_202
    action: search
    default: Intercity/2.0.0/search/search_station_code_2/default.yaml
    message_id: true
  - code: 117
    action_id: search_BUS_203
    action: search
    default: Intercity/2.0.0/search/search_station_code_3/default.yaml
    message_id: true
  - code: 118
    action_id: on_search_BUS_201
    action: on_search
    default: Intercity/2.0.0/on_search/on_search_station_code_1/default.yaml
    message_id: false
  - code: 119
    action_id: on_search_BUS_202
    action: on_search
    default: Intercity/2.0.0/on_search/on_search_station_code_2/default.yaml
    message_id: false
  - code: 120
    action_id: on_search_BUS_203
    action: on_search
    default: Intercity/2.0.0/on_search/on_search_station_code_3/default.yaml
    message_id: false
  - code: 121
    action_id: select_BUS_201
    action: select
    default: Intercity/2.0.0/select/select_station_code_1/default.yaml
    message_id: true
  - code: 122
    action_id: select_BUS_202
    action: select
    default: Intercity/2.0.0/select/select_station_code_2/default.yaml
    message_id: true
  - code: 123
    action_id: on_select_BUS_201
    action: on_select
    default: Intercity/2.0.0/on_select/on_select_station_code_1/default.yaml
    message_id: false
  - code: 124
    action_id: on_select_BUS_202
    action: on_select
    default: Intercity/2.0.0/on_select/on_select_station_code_2/default.yaml
    message_id: false
  - code: 125
    action_id: on_select_BUS_221
    action: on_select
    default: Intercity/2.0.0/on_select/on_select_error_response/default.yaml
    message_id: false
  - code: 126
    action_id: init_BUS_201
    action: init
    default: Intercity/2.0.0/init/init_station_code/default.yaml
    message_id: true
  - code: 127
    action_id: init_BUS_221
    action: init
    default: Intercity/2.0.0/init/init_error_response/default.yaml
    message_id: true
  - code: 128
    action_id: on_init_BUS_201
    action: on_init
    default: Intercity/2.0.0/on_init/on_init_station_code/default.yaml
    message_id: false
  - code: 129
    action_id: on_init_BUS_221
    action: on_init
    default: Intercity/2.0.0/on_init/on_init_error_response/default.yaml
    message_id: false
  - code: 130
    action_id: confirm_BUS_201
    action: confirm
    default: Intercity/2.0.0/confirm/confirm_station_code/default.yaml
    message_id: true
  - code: 131
    action_id: confirm_BUS_241
    action: confirm
    default: Intercity/2.0.0/confirm/confirm_seller_cancellation/default.yaml
    message_id: true
  - code: 132
    action_id: on_confirm_BUS_201
    action: on_confirm
    default: Intercity/2.0.0/on_confirm/on_confirm_station_code/default.yaml
    message_id: false
  - code: 133
    action_id: on_confirm_BUS_211
    action: unsolicited_on_confirm
    default: Intercity/2.0.0/on_confirm/on_confirm_cancel_flow/default.yaml
    message_id: true
  - code: 134
    action_id: on_confirm_BUS_231
    action: unsolicited_on_confirm
    default: Intercity/2.0.0/on_confirm/on_confirm_partial_cancellation/default.yaml
    message_id: true
  - code: 135
    action_id: on_confirm_BUS_241
    action: on_confirm
    default: Intercity/2.0.0/on_confirm/on_confirm_seller_cancellation/default.yaml
    message_id: false
  - code: 136
    action_id: on_confirm_BUS_251
    action: on_confirm
    default: Intercity/2.0.0/on_confirm/on_confirm_rating_success/default.yaml
    message_id: false
  - code: 137
    action_id: on_confirm_BUS_261
    action: on_confirm
    default: Intercity/2.0.0/on_confirm/on_confirm_rating_error/default.yaml
    message_id: true
  - code: 138
    action_id: cancel_BUS_211
    action: cancel
    default: Intercity/2.0.0/cancel/cancel_cancel_flow_1/default.yaml
    message_id: true
  - code: 139
    action_id: cancel_BUS_212
    action: cancel
    default: Intercity/2.0.0/cancel/cancel_cancel_flow_2/default.yaml
    message_id: true
  - code: 140
    action_id: on_cancel_BUS_211
    action: on_cancel
    default: Intercity/2.0.0/on_cancel/on_cancel_cancel_flow_1/default.yaml
    message_id: false
  - code: 141
    action_id: on_cancel_BUS_212
    action: on_cancel
    default: Intercity/2.0.0/on_cancel/on_cancel_cancel_flow_2/default.yaml
    message_id: false
  - code: 142
    action_id: on_cancel_BUS_241
    action: on_cancel
    default: Intercity/2.0.0/on_cancel/on_cancel_seller_cancellation/default.yaml
    message_id: false
  - code: 143
    action_id: status_BUS_201
    action: status
    default: Intercity/2.0.0/status/status_station_code/default.yaml
    message_id: true
  - code: 144
    action_id: on_status_BUS_201
    action: on_status
    default: Intercity/2.0.0/on_status/on_status_station_code_1/default.yaml
    message_id: false
  - code: 145
    action_id: on_status_unsolicited_201
    action: on_status
    default: Intercity/2.0.0/on_status/on_status_station_code_2/default.yaml
    message_id: true
  - code: 146
    action_id: on_status_BUS_251
    action: on_status
    default: Intercity/2.0.0/on_status/on_status_rating_success/default.yaml
    message_id: false
  - code: 147
    action_id: on_status_BUS_261
    action: on_status
    default: Intercity/2.0.0/on_status/on_status_rating_error/default.yaml
    message_id: false
  - code: 148
    action_id: update_BUS_231
    action: update
    default: Intercity/2.0.0/update/update_partial_cancellation_flow_1/default.yaml
    message_id: true
  - code: 149
    action_id: update_BUS_232
    action: update
    default: Intercity/2.0.0/update/update_partial_cancellation_flow_2/default.yaml
    message_id: true
  - code: 150
    action_id: on_update_BUS_231
    action: on_update
    default: Intercity/2.0.0/on_update/on_update_partial_cancellation_flow_1/default.yaml
    message_id: false
  - code: 151
    action_id: on_update_BUS_232
    action: on_update
    default: Intercity/2.0.0/on_update/on_update_partial_cancellation_flow_2/default.yaml
    message_id: false
  - code: 152
    action_id: rating_251
    action: rating
    default: Intercity/2.0.0/rating/rating_success/default.yaml
    message_id: true
  - code: 153
    action_id: rating_261
    action: rating
    default: Intercity/2.0.0/rating/rating_error/default.yaml
    message_id: true
  - code: 154
    action_id: on_rating_261
    action: on_rating
    default: Intercity/2.0.0/on_rating/on_rating_error/default.yaml
    message_id: false
  - code: 155
    action_id: select_BUS_221
    action: select
    default: Intercity/2.0.0/select/select_error_response/default.yaml
    message_id: true
