session_data:
  transaction_id: null
  message_id: null
  last_action: null
  mock_type: null
  city_code: null
  bap_id: null
  bap_uri: null
  bpp_id: null
  bpp_uri: null
  start_location: null
  intermediate_location: null
  end_location: null
  buyer_app_fee: null
  vehicle_type: null
  fulfillments: []
  category_ids: []
  provider_id: null
  fulfillment_ids: []
  item_ids: []
  items: []
  selected_items: []
  selected_item_id: null
  billing: {}
  payments: []
  updated_payments: []
  order_id: null
  status: null
  error_code: null
  error_message: null
  quote: null
  ref_id: null
  ttl: null
  usecaseId: null
  stops: []
  update_stop: []
  update_quote: []
  selected_fulfillments: []
  bap_items: []
  collected_by: null
  updated_price: null
  selected_add_ons: []
  created_at: null
  cancellation_reason_id: null
  cancellation_quote: []
  selected_fulfillment_id: null
  search_1_items: []
  on_search_1_providers: []
  on_search_1_tags: []
  on_search_3_tags: []
  on_search_4_provider_payments: []
  select_1_items: []
  select_1_fulfillments: []
  on_select_1_items: []
  on_select_1_fulfillments: []
  on_select_2_items: []
  on_select_2_fulfillments: []
  init_payments: []
  init_items: []
  init_fulfillments: []
  select_2_items: []
  select_2_fulfillments: []
  on_init_provider: null
  on_init_items: []
  on_init_fulfillments: []
  on_init_payments: []
  confirm_payments: []
  on_confirm_items: []
  on_confirm_fulfillments: []
  on_confirm_payments: []
  on_confirm_cancellation_terms: []
