order:
  id: O1
  provider:
    id: P1
  items:
    - id: I1-2
      parent_item_id: I1
      quantity:
        selected:
          count: 1
      add_ons:
        - id: A1
          quantity:
            selected:
              count: 1
    - id: I1-3
      parent_item_id: I1
      quantity:
        selected:
          count: 1
      add_ons:
        - id: A2
          quantity:
            selected:
              count: 1
    - id: I1-4
      parent_item_id: I1
      quantity:
        selected:
          count: 1
    - id: I2-1
      parent_item_id: I1
      quantity:
        selected:
          count: 1
      add_ons:
        - id: A1
          quantity:
            selected:
              count: 1
    - id: I2-2
      parent_item_id: I1
      quantity:
        selected:
          count: 1
  fulfillments:
    - id: F1
      stops:
        - id: S1
        - id: S2
      vehicle:
        category: AIRLINE
        code: "6E284"
    - id: FT_1
      customer:
        person:
          name: "Mr. | Joe | Wick | Adams"
          age: "30"
          gender: MALE
          dob: "2023-03-23"
        contact:
          phone: "+91-9988776655"
          email: "joeadams@yahoo.com"
    - id: FT_2
      customer:
        person:
          name: "Ms. | Maria | Wick | Adams"
          age: "37"
          gender: FEMALE
          dob: "2001-03-23"
        contact:
          phone: "+91-9988776655"
          email: "joeadams@yahoo.com"
    - id: FT_3
      customer:
        person:
          name: "Mr. | Mick | Wick | Adams"
          age: "20"
          gender: MALE
          dob: "2001-03-23"
        contact:
          phone: "+91-9988776655"
          email: "joeadams@yahoo.com"
    - id: FT_4
      customer:
        person:
          name: "Mr. | Alex | Wick | Adams"
          age: "31"
          gender: MALE
          dob: "2001-03-23"
        contact:
          phone: "+91-9988776655"
          email: "joeadams@yahoo.com"
    - id: FT_5
      customer:
        person:
          name: "Mr. | John | Nick | Adams"
          age: "30"
          gender: MALE
          dob: "2001-03-23"
        contact:
          phone: "+91-9988776655"
          email: "joeadams@yahoo.com"
  billing:
    name: Joe Adams
    phone: "+91-9988776655"
    tax_id: GSTIN:22AAAAA0000A1Z5
  payments:
    - id: PA1
      collected_by: BAP
      status: PAID
      type: PRE-ORDER
      params:
        transaction_id: a1644304-d150-4a58-93fe-69e8ab6e3cdc
        currency: INR
        amount: "42159"
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: SETTLEMENT_AMOUNT
              value: "10421"
            - descriptor:
                code: SETTLEMENT_TYPE
              value: neft
            - descriptor:
                code: DELAY_INTEREST
              value: "2.5"
            - descriptor:
                code: STATIC_TERMS
              value: https://api.example-bap.com/booking/terms
