intent:
  fulfillment:
    id: F1
    stops:
      - id: S2
        type: PICKUP
      - id: S5
        type: DROP
  provider:
    id: P1
  payment:
    tags:
      - descriptor:
          code: BUYER_FINDER_FEES
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
          - descriptor:
              code: BUYER_FINDER_FEES_TYPE
            value: percent
      - descriptor:
          code: SETTLEMENT_TERMS
        display: false
        list:
          - descriptor:
              code: DELAY_INTEREST
            value: "2.5"
          - descriptor:
              code: STATIC_TERMS
            value: https://api.example-bap.com/booking/terms
