save-data:
  payments: "$.message.order.payments[*]"
  payment_id: "$.message.order.payments[*].id"
  tags: "$.message.order.tags"
  on_init_tags: "$.message.order.tags"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri" 