order:
  items:
    - id: ITEM_ID_GOLD_LOAN_1
      xinput:
        form:
          id: FO3
        form_response:
          status: SUCCESS
          submission_id: F03_SUBMISSION_ID

  payments:
    - collected_by: BPP
      params:
        bank_account_number: xxxxxxxxxxxxxx
        bank_code: XXXXXXXX
        virtual_payment_address: 9988199772@okicic
      status: NOT-PAID
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_TYPE
              value: percent-annualized
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: SETTLEMENT_AMOUNT
              value: "1159"
            - descriptor:
                code: SETTLEMENT_TYPE
              value: neft
            - descriptor:
                code: DELAY_INTEREST
              value: "5"
            - descriptor:
                code: STATIC_TERMS
              value: https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan
            - descriptor:
                code: OFFLINE_CONTRACT
              value: "true"
      type: ON_ORDER

  provider:
    id: PROVIDER_ID
