catalog:
  descriptor:
    name: ABC Fights Services Solutions
    images:
      - url: https://abc-AIRLINE.in/logos/logo.ico
        size_type: xs

  providers:
    - id: P1
      descriptor:
        name: ABC Operator Fights Services
        images:
          - url: https://operator1.com/logos/logo.ico
            size_type: xs

      categories:
        - id: C1
          descriptor:
            name: Economy
            code: ECONOMY
        - id: C2
          descriptor:
            name: Premium Economy
            code: PREMIUM_ECONOMY
        - id: C3
          descriptor:
            name: Business
            code: BUSINESS
        - id: C4
          descriptor:
            name: First Class
            code: FIRST_CLASS

      items:
        - id: I1
          descriptor:
            name: Adult
            code: ADULT_TICKET
          quantity:
            selected:
              count: 3
          category_ids: [C1]
          time:
            label: JOURNEY_TIME
            duration: PT16H30M
          refund_terms:
            - refund_eligible: true
          cancellation_terms:
            - external_ref:
                url: https://api.example-bpp.com/pilot/bpp/v1/cancellation_terms.pdf
                mimetype: application/pdf
          add_ons:
            - id: A1
              descriptor:
                name: meals
                code: MEALS
              quantity:
                available:
                  count: 1
              price:
                currency: INR
                value: "300"
            - id: A2
              descriptor:
                name: Delayed and Lost Baggage Protection
                code: BAGGAGE
              quantity:
                available:
                  count: 1
              price:
                currency: INR
                value: "500"
            - id: A3
              descriptor:
                name: Fast Forward
                code: FAST_FORWARD
                short_desc: Get priority check-in & baggage handling services to save time.
              quantity:
                available:
                  count: 1
              price:
                currency: INR
                value: "200"
            - id: A4
              descriptor:
                name: Travel Assistance
                code: TRAVEL_ASSISTANCE
              quantity:
                available:
                  count: 1
              price:
                currency: INR
                value: "500"
            - id: A7
              descriptor:
                name: Free Cancellation
                code: FREE_CANCELLATION
              price:
                currency: INR
                value: "500"
            - id: A8
              descriptor:
                name: Free Date Changes
                code: FREE_DATE_CHANGE
              price:
                currency: INR
                value: "200"
          tags:
            - descriptor:
                code: FARE_TYPE
                name: Fare Type
              display: true
              list:
                - descriptor: { code: REGULAR }
                - descriptor: { code: STUDENT }
                - descriptor: { code: SENIOR_CITIZEN }
                - descriptor: { code: ARMED_FORCES }
                - descriptor: { code: DOCTORS_NURSES }
            - descriptor:
                code: GENERAL_INFO
                name: General Info
              display: true
              list:
                - descriptor:
                    code: CABIN_BAGGAGE
                    name: Cabin Baggage
                    short_desc: Allowed limit for cabin baggage
                  value: 7 KG
                - descriptor:
                    code: CHECK_IN_BAGGAGE
                    name: Check-in Baggage
                    short_desc: Allowed limit for checkin baggage
                  value: 15 KG
                - descriptor:
                    code: PROHIBITED_ITEMS
                    name: Prohibited Items
                  value: list of items

        # Similarly items I2, I3, I4 follow same structure as I1 but with different counts

      payments:
        - tags:
            - descriptor:
                code: BUYER_FINDER_FEES
              display: false
              list:
                - descriptor:
                    code: BUYER_FINDER_FEES_PERCENTAGE
                  value: "1"
            - descriptor:
                code: SETTLEMENT_TERMS
              display: false
              list:
                - descriptor:
                    code: SETTLEMENT_WINDOW
                  value: PT30D
                - descriptor:
                    code: SETTLEMENT_BASIS
                  value: INVOICE_RECEIPT
                - descriptor:
                    code: MANDATORY_ARBITRATION
                  value: "TRUE"
                - descriptor:
                    code: COURT_JURISDICTION
                  value: New Delhi
                - descriptor:
                    code: STATIC_TERMS
                  value: https://api.example-bpp.com/booking/terms

  tags:
    - descriptor:
        code: PAGINATION
        name: Pagination
      display: true
      list:
        - descriptor: { code: PAGINATION_ID }
          value: P1
        - descriptor: { code: MAX_PAGE_NUMBER }
          value: "3"
