save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  start_code: "$.message.intent.fulfillment.stops[?(@.type=='START')].location.descriptor.code"
  end_code: "$.message.intent.fulfillment.stops[?(@.type=='END')].location.descriptor.code"
  vehicle_type: "$.message.intent.fulfillment.vehicle.category"
  buyer_app_fee: "$.message.intent.payment.tags[?(@.descriptor.code=='BUYER_FINDER_FEES')].list[?(@.descriptor.code=='BUYER_FINDER_FEES_PERCENTAGE')].value"
  city_code: "$.context.location.city.code"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
