order:
  provider:
    id: P1
  items:
    - id: I1
      quantity:
        selected:
          count: 3
    - parent_item_id: I1
      quantity:
        selected:
          count: 1
      add_ons:
        - id: A1
          quantity:
            selected:
              count: 1
    - parent_item_id: I1
      quantity:
        selected:
          count: 1
      add_ons:
        - id: A2
          quantity:
            selected:
              count: 1
    - parent_item_id: I1
      quantity:
        selected:
          count: 1
    - parent_item_id: I2
      quantity:
        selected:
          count: 1
      add_ons:
        - id: A1
          quantity:
            selected:
              count: 1
    - parent_item_id: I2
      quantity:
        selected:
          count: 1
  fulfillments:
    - id: F1
      stops:
        - id: S1
        - id: S2
