
  catalog:
    fulfillments:
      - id: "TYPE1"
        type: "BPP_ONLINE_EMAIL_SMS"
      - id: "TYPE2"
        type: "BPP_ONLINE_EMAIL"
      - id: "TYPE3"
        type: "BPP_ONLINE_SMS"
      - id: "TYPE4"
        type: "BPP_OFFLINE"
      - id: "TYPE5"
        type: "BAP"
    descriptor:
      name: "Gift card store"
      symbol: "https://giftcard.com/images/1-image"
      short_desc: "Online Gift Card Store"
      long_desc: "Online Gift Card Store"
      images:
        - url: "https://giftcard.com/images/store-image"
    providers:
      - id: "P1"
        ttl: "P1D"
        time:
          label: "ENABLE"
          timestamp: "2023-03-10T10:00:00.402Z"
        descriptor:
          name: "Gift card store"
          symbol: "https://giftcard.com/images/1-image"
          short_desc: "Online Gift Card Store"
          long_desc: "Online Gift Card Store"
          images:
            - url: "https://giftcard.com/images/store-image"
        categories:
          - id: "C1"
            descriptor:
              code: "CARD"
          - id: "C2"
            descriptor:
              code: "PROMO"
          - id: "C3"
            descriptor:
              code: "E_PAY"
          - id: "C4"
            descriptor:
              code: "E_RUPI"
        items:
          - id: "BaseCard1"
            descriptor:
              name: "Gift Card"
              code: "PARENT"
              symbol: "https://giftcard.com/images/01.png"
              short_desc: "Birthday Gift Card"
              long_desc: "Birthday Gift Card"
              images:
                - url: "https://giftcard.com/images/02.png"
            tags:
              - descriptor:
                  code: "BRAND_DETAILS"
                list:
                  - descriptor:
                      code: "BRAND_NAME"
                    value: "name of brand free text"
              - descriptor:
                  code: "VARIANT_FIELDS"
                list:
                  - descriptor:
                      code: "items.tags.ITEM_DETAILS.OCCASION"
                  - descriptor:
                      code: "items.price.value"
              - descriptor:
                  code: "ITEM_DETAILS"
                list:
                  - descriptor:
                      code: "TERMS_CONDITION"
                    value: "https://giftcard.com/giftcards/tncs"
                  - descriptor:
                      code: "CATEGORY"
                    value: "FASHION"
            category_ids:
              - "C1"
            fulfillment_ids:
              - "TYPE1"
            cancellation_terms:
              - cancel_eligible: false
            return_terms:
              - return_eligible: false
          - id: "Detail1"
            parent_item_id: "BaseCard1"
            descriptor:
              code: "PARENT"
            tags:
              - descriptor:
                  code: "ITEM_DETAILS"
                list:
                  - descriptor:
                      code: "OCCASION"
                    value: "DIWALI"
          - id: "Detail2"
            parent_item_id: "BaseCard1"
            descriptor:
              code: "PARENT"
            tags:
              - descriptor:
                  code: "ITEM_DETAILS"
                list:
                  - descriptor:
                      code: "OCCASION"
                    value: "BIRTHDAY"
          - id: "GC1"
            parent_item_id: "Detail1"
            descriptor:
              code: "ITEM"
            price:
              currency: "INR"
              value: "1500"
              offered_value: "2000"
          - id: "GC2"
            parent_item_id: "Detail2"
            descriptor:
              code: "ITEM"
            price:
              currency: "INR"
              value: "2000"
              offered_value: "2000"
          - id: "GC3"
            parent_item_id: "Detail1"
            descriptor:
              code: "ITEM"
            price:
              currency: "INR"
              value: "2000"
              offered_value: "2000"
          - id: "GC4"
            parent_item_id: "Detail2"
            descriptor:
              code: "ITEM"
            price:
              currency: "INR"
              value: "1500"
              offered_value: "1500"
          - id: "GC5"
            descriptor:
              name: "Birthday Gift Card"
              code: "ITEM"
              symbol: "https://giftcard.com/images/01.png"
              short_desc: "Birthday Gift Card"
              long_desc: "Birthday Gift Card"
              images:
                - url: "https://giftcard.com/images/02.png"
            price:
              currency: "INR"
              minimum_value: "1000"
              maximum_value: "10000"
            tags:
              - descriptor:
                  code: "BRAND_DETAILS"
                list:
                  - descriptor:
                      code: "BRAND_NAME"
                    value: "name of brand free text"
            category_ids:
              - "C1"
            fulfillment_ids:
              - "TYPE1"
            cancellation_terms:
              - cancel_eligible: false
            return_terms:
              - return_eligible: false
          - id: "SAMPLE_GC"
            descriptor:
              name: "TRAVEL Gift Card"
              code: "ITEM"
              symbol: "https://giftcard.com/images/01.png"
              short_desc: "BOOK CAB AND GET 100 OFF"
              long_desc: "BOOK CAB AND GET 100 OFF"
              images:
                - url: "https://giftcard.com/images/02.png"
            price:
              currency: "INR"
              value: "100"
              offered_value: "100"
            tags:
              - descriptor:
                  code: "BRAND_DETAILS"
                list:
                  - descriptor:
                      code: "BRAND_NAME"
                    value: "name of brand free text"
            category_ids:
              - "C1"
            fulfillment_ids:
              - "TYPE1"
            cancellation_terms:
              - cancel_eligible: false
            return_terms:
              - return_eligible: false
        offers:
          - id: "DISCA100"
            descriptor:
              code: "DISCOUNT"
              short_desc: "Get 20% discount"
              images:
                - url: "https://sellerapp.com/images/offerbanner.png"
            item_ids:
              - "GC1"
            time:
              range:
                start: "2023-06-01T16:00:00.000Z"
                end: "2023-06-01T23:00:00.000Z"
            tags:
              - descriptor:
                  code: "QUALIFIER"
                list:
                  - descriptor:
                      code: "MIN_VALUE"
                    value: "1000"
              - descriptor:
                  code: "BENEFIT"
                list:
                  - descriptor:
                      code: "VALUE_TYPE"
                    value: "AMOUNT"
                  - descriptor:
                      code: "VALUE"
                    value: "100"
              - descriptor:
                  code: "META"
                list:
                  - descriptor:
                      code: "ADDITIVE"
                    value: "TRUE"
                  - descriptor:
                      code: "AUTO"
                    value: "FALSE"
          - id: "FREEBIE123"
            descriptor:
              code: "FREEBIE"
              short_desc: "Get 20% discount"
              images:
                - url: "https://sellerNP.com/images/offerbanner2.png"
            item_ids:
              - "GC2"
            time:
              label: "VALID"
              range:
                start: "2024-03-06T05:32:08.028Z"
                end: "2024-03-06T05:32:08.028Z"
            tags:
              - descriptor:
                  code: "QUALIFIER"
                list:
                  - descriptor:
                      code: "ITEM_COUNT"
                    value: "1"
              - descriptor:
                  code: "BENEFIT"
                list:
                  - descriptor:
                      code: "ITEM_ID"
                    value: "SAMPLE_GC"
                  - descriptor:
                      code: "ITEM_COUNT"
                    value: "1"
              - descriptor:
                  code: "META"
                list:
                  - descriptor:
                      code: "ADDITIVE"
                    value: "FALSE"
                  - descriptor:
                      code: "AUTO"
                    value: "TRUE" 