order:
  provider:
    id: P1
    descriptor:
      name: ABC Operator Fights Services
      images:
        - url: https://operator1.com/logos/logo.ico
          size_type: xs

  items:
    - id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 3
      category_ids: [C1]
      fulfillment_ids: [F1]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I1-1
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_1]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A1
          descriptor:
            name: meals
            code: MEALS
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "300"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I1-2
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_2]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A2
          descriptor:
            name: Delayed and Lost Baggage Protection
            code: BAGGAGE
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "500"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I1-3
      parent_item_id: I1
      descriptor:
        name: Adult
        code: ADULT_TICKET
      price:
        currency: INR
        value: "9280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_3]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I2
      descriptor:
        name: Child
        code: CHILD_TICKET
      price:
        currency: INR
        value: "4280"
      quantity:
        selected:
          count: 2
      category_ids: [C1]
      fulfillment_ids: [F1]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I2-1
      descriptor:
        name: Child
        code: CHILD_TICKET
      price:
        currency: INR
        value: "4280"
      quantity:
        selected:
          count: 1
      category_ids: [C1]
      fulfillment_ids: [F1, FT_4]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      add_ons:
        - id: A1
          descriptor:
            name: meals
            code: MEALS
          quantity:
            selected:
              count: 1
          price:
            currency: INR
            value: "300"
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

    - id: I2-2
      descriptor:
        name: Child
        code: CHILD_TICKET
      price:
        currency: INR
        value: "4280"
      quantity:
        selected:
          count: 2
      category_ids: [C1]
      fulfillment_ids: [F1, FT_5]
      time:
        label: JOURNEY_TIME
        duration: PT16H30M
      refund_terms:
        - refund_eligible: true
      tags:
        - descriptor:
            code: FARE_TYPE
            name: Fare Type
          display: true
          list:
            - descriptor: { code: REGULAR }
            - descriptor: { code: STUDENT }
            - descriptor: { code: SENIOR_CITIZEN }
            - descriptor: { code: ARMED_FORCES }
            - descriptor: { code: DOCTORS_NURSES }
        - descriptor:
            code: GENERAL_INFO
            name: General Info
          display: true
          list:
            - descriptor:
                code: CABIN_BAGGAGE
                name: Cabin Baggage
                short_desc: Allowed limit for cabin baggage
              value: "7 KG"
            - descriptor:
                code: CHECK_IN_BAGGAGE
                name: Check-in Baggage
                short_desc: Allowed limit for checkin baggage
              value: "15 KG"
            - descriptor:
                code: PROHIBITED_ITEMS
                name: Prohibited Items
              value: list of items

  fulfillments:
    - id: F1
      type: TRIP
      stops:
        - id: S1
          type: START
          location:
            descriptor:
              name: Delhi
              code: DEL
          time:
            label: DATE_TIME
            timestamp: "2023-10-15T20:00:00.000Z"
