save-data:
  cityCode: "$.context.location.city.code"
  bap_id: "$.context.bap_id"
  bap_uri: "$.context.bap_uri"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  price: "$.message.order.quote.price.value"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.order.quote"
  provider: "$.message.order.provider"
  time_range: "$.message.order.provider.time"
  tags: "$.message.order.tags"
  select_tags: "$.message.order.tags"
  cancellation_terms: "$.message.order.cancellation_terms"

