order:
  items:
    - id: I1
      quantity:
        selected:
          count: 2
  fulfillments:
    - id: F1
      stops:
        - id: S2
          type: PICKUP
        - id: S5
          type: DROP
    - id: FT1
      tags:
        - descriptor:
            code: SEAT_GRID
          list:
            - descriptor:
                code: NUMBER
              value: A1
            - descriptor:
                code: SELECTED
              value: "true"
            - descriptor:
                code: ITEM_ID
              value: I1
    - id: FT2
      tags:
        - descriptor:
            code: SEAT_GRID
          list:
            - descriptor:
                code: NUMBER
              value: F1
            - descriptor:
                code: SELECTED
              value: "true"
            - descriptor:
                code: ITEM_ID
              value: I1
  provider:
    id: P1
