
  intent:
    category:
      descriptor:
        code: "CARD"
    payment:
      tags:
        - descriptor:
            code: "BUYER_FINDER_FEES"
          list:
            - descriptor:
                code: "BUYER_FINDER_FEES_PERCENTAGE"
              value: "3"
            - descriptor:
                code: "BUYER_FINDER_FEES_VALUE"
              value: "100" 