order:
  id: O1
  status: ACTIVE
  items:
    - id: I1
      descriptor:
        name: Seater Ticket
        code: SEAT
      price:
        currency: INR
        value: "800"
      quantity:
        selected:
          count: 2
      fulfillment_ids:
        - F1
        - FT1
        - FT2
      category_ids:
        - C1
  provider:
    id: P1
    descriptor:
      name: ABC Operator 1 Bus Services
      images:
        - url: https://operator1.com/logos/logo.ico
  fulfillments:
    - id: F1
      type: TRIP
      state:
        descriptor:
          code: CONFIRMED
      stops:
        - id: S2
          type: PICKUP
          location:
            descriptor:
              name: Agara
              code: std:080-pincode:560034
            gps: 12.924479, 77.648999
          time:
            label: DATE_TIME
            timestamp: "2023-09-06T06:30:00.000Z"
          authorization:
            type: PNR
            token: RB3F9K7H
            status: UNCLAIMED
        - id: S5
          type: DROP
          location:
            descriptor:
              name: Ameerpet
              code: std:040-pincode:500016
            gps: 17.441586, 78.441581
          time:
            label: DATE_TIME
            timestamp: "2023-09-06T15:10:00.000Z"
      vehicle:
        category: BUS
        variant: AC
        capacity: 47
        wheels_count: "6"
        energy_type: DIESEL
    - id: FT1
      type: TICKET
      state:
        descriptor:
          code: CONFIRMED
      customer:
        person:
          name: Joe Adams
          age: "30"
          gender: MALE
        contact:
          phone: "+91-9988776655"
      tags:
        - descriptor:
            code: SEAT_GRID
          list:
            - descriptor: {code: X}
              value: "0"
            - descriptor: {code: Y}
              value: "0"
            - descriptor: {code: Z}
              value: "0"
            - descriptor: {code: X_SIZE}
              value: "1"
            - descriptor: {code: Y_SIZE}
              value: "1"
            - descriptor: {code: NUMBER}
              value: A1
            - descriptor: {code: RESTRICTED_GENDER}
              value: FEMALE
            - descriptor: {code: SINGLE_SEAT}
              value: TRUE
            - descriptor: {code: SEAT_PRICE}
              value: "50"
            - descriptor: {code: SELECTED}
              value: "true"
            - descriptor: {code: SELECTED_SEAT}
              value: A1
            - descriptor: {code: ITEM_ID}
              value: I1
    - id: FT2
      type: TICKET
      state:
        descriptor:
          code: CONFIRMED
      customer:
        person:
          name: RACHEL ADAMS
          age: "27"
          gender: FEMALE
        contact:
          phone: "+91-9723797890"
      tags:
        - descriptor:
            code: SEAT_GRID
          list:
            - descriptor: {code: X}
              value: "1"
            - descriptor: {code: Y}
              value: "0"
            - descriptor: {code: Z}
              value: "1"
            - descriptor: {code: X_SIZE}
              value: "1"
            - descriptor: {code: Y_SIZE}
              value: "2"
            - descriptor: {code: NUMBER}
              value: F1
            - descriptor: {code: RESTRICTED_GENDER}
              value: MALE
            - descriptor: {code: SINGLE_SEAT}
              value: TRUE
            - descriptor: {code: SEAT_PRICE}
              value: "50"
            - descriptor: {code: SELECTED}
              value: "true"
            - descriptor: {code: SELECTED_SEAT}
              value: F1
            - descriptor: {code: ITEM_ID}
              value: I1
  cancellation_terms:
    - external_ref:
        mimetype: text/html
        url: https://api.unreserved-entry-pass.com/beckn/tnc.html
      cancellation_eligible: true
    - cancellation_fee:
        percentage: "10"
      fulfillment_state:
        descriptor:
          code: CONFIRMED
      cancel_by:
        label: DURATION
        duration: PT1H30M
      cancellation_eligible: true
  quote:
    price:
      value: "1783"
      currency: INR
    breakup:
      - title: BASE_FARE
        price:
          currency: INR
          value: "1600"
        item:
          id: I1
          price:
            currency: INR
            value: "800"
          quantity:
            selected:
              count: 2
      - title: TAX
        price:
          currency: INR
          value: "64"
        item:
          tags:
            - descriptor:
                code: TAX
              list:
                - descriptor: {code: CGST}
                  value: 2%
                - descriptor: {code: SGST}
                  value: 2%
                - descriptor: {code: SERVICE_TAX}
                  value: 2%
      - title: CONVENIENCE_FEE
        price:
          currency: INR
          value: "19"
      - title: SEAT_FARE
        price:
          value: "50"
          currency: INR
        item:
          id: I1
          fulfillment_ids:
            - FT1
      - title: SEAT_FARE
        price:
          value: "50"
          currency: INR
        item:
          id: I1
          fulfillment_ids:
            - FT2
      - title: SELLER_FEES
        price:
          currency: INR
          value: "0"
        item:
          tags:
            - descriptor:
                code: SELLER_FEES
              list:
                - descriptor: {name: TotReservationFare}
                  value: "0"
                - descriptor: {name: TotSRTFee}
                  value: "0"
                - descriptor: {name: TotTollFee}
                  value: "0"
                - descriptor: {name: concessionAmount}
                  value: "0"
                - descriptor: {name: roundOfFee}
                  value: "0"
    ttl: PT10M
  payments:
    - id: PA1
      collected_by: BAP
      status: PAID
      type: PRE-ORDER
      params:
        transaction_id: a1644304-d150-4a58-93fe-69e8ab6e3cdc
        currency: INR
        amount: "1783"
        bank_code: XXXXXXXX
        bank_account_number: xxxxxxxxxxxxxx
        virtual_payment_address: 9988199772@okicic
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: SETTLEMENT_WINDOW
              value: PT60M
            - descriptor:
                code: SETTLEMENT_BASIS
              value: Delivery
            - descriptor:
                code: SETTLEMENT_TYPE
              value: UPI
            - descriptor:
                code: MANDATORY_ARBITRATION
              value: "true"
            - descriptor:
                code: COURT_JURISDICTION
              value: New Delhi
            - descriptor:
                code: DELAY_INTEREST
              value: "2.5"
            - descriptor:
                code: STATIC_TERMS
              value: https://www.abc.com/settlement-terms/
            - descriptor:
                code: SETTLEMENT_AMOUNT
              value: "1766"
  created_at: "2023-09-03T01:55:08.143Z"
  updated_at: "2023-09-03T01:55:08.143Z"
