message:
  intent:
    fulfillment:
      stops:
        - type: START
          location:
            descriptor:
              code: KASHMERE_GATE
        - type: END
          location:
            descriptor:
              code: GREATER_KAILASH
      vehicle:
        category: BUS
    payment:
      collected_by: BPP
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: '3'
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: DELAY_INTEREST
              value: '2.5'
            - descriptor:
                code: STATIC_TERMS
              value: 'https://api.example-bap.com/booking/terms'
