message:
  catalog:
    descriptor:
      name: Transit Solutions
      images:
        - url: 'https://transitsolutions.in/logos/logo.ico'
          size_type: xs
    providers:
      - id: P1
        descriptor:
          name: Delhi Transport Corporation
          images:
            - url: >-
                https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
              size_type: xs
        items:
          - id: I1
            descriptor:
              name: Single Journey Ticket
              code: SJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: '35'
            quantity:
              maximum:
                count: 6
              minimum:
                count: 1
            time:
              label: Validity
              duration: PT2D
              timestamp: '2021-03-23T11:01:40.065Z'
          - id: I2
            descriptor:
              name: Special Fair Single Journey Ticket
              code: SFSJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: '25'
            quantity:
              maximum:
                count: 6
              minimum:
                count: 1
            tags:
              - descriptor:
                  code: FARE_POLICY
                list:
                  - descriptor:
                      code: RESTRICTED_PERSON
                    value: STUDENT
                  - descriptor:
                      code: RESTRICTION_PROOF
                    value: STUDENT_ID
          - id: I3
            descriptor:
              name: Special Fair Single Journey Ticket
              code: SFSJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: '20'
            quantity:
              maximum:
                count: 6
              minimum:
                count: 1
            tags:
              - descriptor:
                  code: FARE_POLICY
                list:
                  - descriptor:
                      code: RESTRICTED_PERSON
                    value: SENIOR_CITIZEN
                  - descriptor:
                      code: RESTRICTION_PROOF
                    value: GOVERMENT_ID
          - id: I4
            descriptor:
              name: Single Journey Ticket
              code: SJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: '30'
            quantity:
              maximum:
                count: 6
              minimum:
                count: 1
          - id: I5
            descriptor:
              name: Special Fair Single Journey Ticket
              code: SFSJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: '20'
            quantity:
              maximum:
                count: 6
              minimum:
                count: 1
            tags:
              - descriptor:
                  code: FARE_POLICY
                list:
                  - descriptor:
                      code: RESTRICTED_PERSON
                    value: STUDENT
                  - descriptor:
                      code: RESTRICTION_PROOF
                    value: STUDENT_ID
          - id: I6
            descriptor:
              name: Special Fair Single Journey Ticket
              code: SFSJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: '15'
            quantity:
              maximum:
                count: 6
              minimum:
                count: 1
            tags:
              - descriptor:
                  code: FARE_POLICY
                list:
                  - descriptor:
                      code: RESTRICTED_PERSON
                    value: SENIOR_CITIZEN
                  - descriptor:
                      code: RESTRICTION_PROOF
                    value: GOVERMENT_ID
        fulfillments:
          - id: F1
            type: TRIP
            stops:
              - type: START
                location:
                  descriptor:
                    name: kashmere gate
                    code: KASHMERE_GATE
                  gps: '28.666576, 77.233332'
                id: '1'
              - type: INTERMEDIATE_STOP
                instructions:
                  name: Stop 1
                location:
                  descriptor:
                    name: Indira Gandhi Technical Unviversity
                    code: INDIRA_GANDHI_TECHNICAL_UNIV
                  gps: '28.624097, 77.204991'
                id: '2'
                parent_stop_id: '1'
              - type: INTERMEDIATE_STOP
                instructions:
                  name: Stop 2
                location:
                  descriptor:
                    name: Yamuna Bazar
                    code: YAMUNA_BAZAR
                  gps: '28.625972,77.209917'
                id: '3'
                parent_stop_id: '2'
              - type: INTERMEDIATE_STOP
                instructions:
                  name: Stop 3
                location:
                  descriptor:
                    name: dhaula kuan
                    code: DHAULA_KUAN
                  gps: '28.610972,77.201717'
                id: '4'
                parent_stop_id: '3'
              - type: INTERMEDIATE_STOP
                instructions:
                  name: Stop 4
                location:
                  descriptor:
                    name: gpo
                    code: GPO
                  gps: '28.623097,77.209917'
                id: '5'
                parent_stop_id: '4'
              - type: END
                location:
                  descriptor:
                    name: Greater Kailash
                    code: GREATER_KAILASH
                  gps: '28.548230, 77.238039'
                id: '6'
                parent_stop_id: '4'
            vehicle:
              category: BUS
            tags:
              - descriptor:
                  code: ROUTE_INFO
                list:
                  - descriptor:
                      code: ROUTE_ID
                    value: '242'
                  - descriptor:
                      code: ROUTE_DIRECTION
                    value: UP
                  - descriptor:
                      code: OPERATIONAL_START_TIME
                    value: '2023-09-14T05:30:00.000Z'
                  - descriptor:
                      code: OPERATIONAL_END_TIME
                    value: '2023-09-14T20:30:00.000Z'
        payments:
          - collected_by: BAP
            tags:
              - descriptor:
                  code: BUYER_FINDER_FEES
                display: false
                list:
                  - descriptor:
                      code: BUYER_FINDER_FEES_PERCENTAGE
                    value: '1'
              - descriptor:
                  code: SETTLEMENT_TERMS
                display: false
                list:
                  - descriptor:
                      code: SETTLEMENT_WINDOW
                    value: P30D
                  - descriptor:
                      code: SETTLEMENT_BASIS
                    value: INVOICE_RECEIPT
                  - descriptor:
                      code: MANDATORY_ARBITRATION
                    value: 'TRUE'
                  - descriptor:
                      code: COURT_JURISDICTION
                    value: New Delhi
                  - descriptor:
                      code: STATIC_TERMS
                    value: 'https://api.transit-solutions.com/booking/terms'
