message:
  catalog:
    descriptor:
      name: Transit Solutions
      images:
        - url: 'https://transitsolutions.in/logos/logo.ico'
          size_type: xs
    providers:
      - id: P1
        descriptor:
          name: Delhi Transport Corporation
          images:
            - url: >-
                https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
              size_type: xs
        items:
          - id: I1
            descriptor:
              name: Single Journey Ticket
              code: SJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            time:
              label: Validity
              duration: PT2D
              timestamp: '2021-03-23T11:01:40.065Z'
          - id: I2
            descriptor:
              name: Special Fair Single Journey Ticket
              code: SFSJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
          - id: I7
            descriptor:
              name: Daily Pass
              code: PASS
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F8
            price:
              currency: INR
              value: '50'
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P1D
          - id: I8
            descriptor:
              name: Weekly Pass
              code: PASS
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F9
            price:
              currency: INR
              value: '100'
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P7D
          - id: I9
            descriptor:
              name: Monthly Pass
              code: PASS
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F9
            price:
              currency: INR
              value: '200'
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P1M
        fulfillments:
          - id: F1
            type: ROUTE
            stops:
              - type: START
                id: '1'
              - type: INTERMEDIATE_STOP
                id: '2'
                parent_stop_id: '1'
              - type: INTERMEDIATE_STOP
                id: '3'
                parent_stop_id: '2'
              - type: INTERMEDIATE_STOP
                id: '4'
                parent_stop_id: '3'
              - type: INTERMEDIATE_STOP
                id: '5'
                parent_stop_id: '4'
              - type: END
                id: '6'
                parent_stop_id: '5'
            vehicle:
              category: BUS
            tags:
              - descriptor:
                  code: ROUTE_INFO
                list:
                  - descriptor:
                      code: ROUTE_ID
                    value: '242'
                  - descriptor:
                      code: ROUTE_DIRECTION
                    value: UP
          - id: F2
            type: ROUTE
            stops:
              - type: START
                id: '6'
              - type: INTERMEDIATE_STOP
                id: '5'
                parent_stop_id: '6'
              - type: INTERMEDIATE_STOP
                id: '4'
                parent_stop_id: '5'
              - type: INTERMEDIATE_STOP
                id: '3'
                parent_stop_id: '4'
              - type: INTERMEDIATE_STOP
                id: '2'
                parent_stop_id: '3'
              - type: END
                id: '1'
                parent_stop_id: '2'
            vehicle:
              category: BUS
            tags:
              - descriptor:
                  code: ROUTE_INFO
                list:
                  - descriptor:
                      code: ROUTE_ID
                    value: '242'
                  - descriptor:
                      code: ROUTE_DIRECTION
                    value: DOWN
          - id: F3
            type: ROUTE
            stops:
              - type: START
                id: '1'
              - type: INTERMEDIATE_STOP
                id: '2'
                parent_stop_id: '1'
              - type: END
                id: '6'
                parent_stop_id: '2'
            vehicle:
              category: BUS
            tags:
              - descriptor:
                  code: ROUTE_INFO
                list:
                  - descriptor:
                      code: ROUTE_ID
                    value: '241'
                  - descriptor:
                      code: ROUTE_DIRECTION
                    value: UP
          - id: F4
            type: ROUTE
            stops:
              - type: START
                id: '6'
              - type: INTERMEDIATE_STOP
                id: '2'
                parent_stop_id: '6'
              - type: END
                id: '1'
                parent_stop_id: '2'
            vehicle:
              category: BUS
            tags:
              - descriptor:
                  code: ROUTE_INFO
                list:
                  - descriptor:
                      code: ROUTE_ID
                    value: '241'
                  - descriptor:
                      code: ROUTE_DIRECTION
                    value: DOWN
          - id: F8
            type: PASS
            customer:
              person:
                creds:
                  - type: PAN
                  - type: AADHAR
                  - type: DL
                  - type: VOTER_ID
            stops:
              - type: START
                location:
                  descriptor:
                    code: 'std:011'
                  gps: '28.666576, 77.233332'
                id: '1'
            vehicle:
              category: BUS
              variant: NON_AC
          - id: F9
            type: PASS
            customer:
              person:
                creds:
                  - type: PAN
                  - type: AADHAR
                  - type: DL
                  - type: VOTER_ID
            stops:
              - type: START
                location:
                  descriptor:
                    code: 'std:011'
                  gps: '28.666576, 77.233332'
                id: '1'
            vehicle:
              category: BUS
              variant: AC
          - id: F10
            type: STOPS
            stops:
              - id: '1'
                location:
                  descriptor:
                    name: MOCK_STATION_1
                    code: MOCK_STATION_1
                  gps: '28.666576, 77.233332'
              - id: '2'
                instructions:
                  name: Stop 1
                location:
                  descriptor:
                    name: MOCK_STATION_2
                    code: MOCK_STATION_2
                  gps: '28.624097, 77.204991'
              - id: '3'
                instructions:
                  name: Stop 2
                location:
                  descriptor:
                    name: MOCK_STATION_3
                    code: MOCK_STATION_3
                  gps: '28.625972,77.209917'
              - id: '4'
                instructions:
                  name: Stop 3
                location:
                  descriptor:
                    name: MOCK_STATION_4
                    code: MOCK_STATION_4
                  gps: '28.610972,77.201717'
              - id: '5'
                instructions:
                  name: Stop 4
                location:
                  descriptor:
                    name: MOCK_STATION_5
                    code: MOCK_STATION_5
                  gps: '28.623097,77.209917'
              - id: '6'
                location:
                  descriptor:
                    name: MOCK_STATION_6
                    code: MOCK_STATION_6
                  gps: '28.548230, 77.238039'
        payments:
          - collected_by: BAP
            tags:
              - descriptor:
                  code: BUYER_FINDER_FEES
                display: false
                list:
                  - descriptor:
                      code: BUYER_FINDER_FEES_PERCENTAGE
                    value: '1'
              - descriptor:
                  code: SETTLEMENT_TERMS
                display: false
                list:
                  - descriptor:
                      code: SETTLEMENT_WINDOW
                    value: P30D
                  - descriptor:
                      code: SETTLEMENT_BASIS
                    value: INVOICE_RECEIPT
                  - descriptor:
                      code: MANDATORY_ARBITRATION
                    value: 'TRUE'
                  - descriptor:
                      code: COURT_JURISDICTION
                    value: New Delhi
                  - descriptor:
                      code: STATIC_TERMS
                    value: 'https://api.transit-solutions.com/booking/terms'
    tags:
      - descriptor:
          code: PAGINATION
          name: Pagination
        display: true
        list:
          - descriptor:
              code: PAGINATION_ID
            value: P1
          - descriptor:
              code: CURRENT_PAGE_NUMBER
            value: '2'
          - descriptor:
              code: MAX_PAGE_NUMBER
            value: '3'