message:
  catalog:
    descriptor:
      name: Transit Solutions
      images:
        - url: 'https://transitsolutions.in/logos/logo.ico'
          size_type: xs
    providers:
      - id: P1
        descriptor:
          name: Delhi Transport Corporation
          images:
            - url: >-
                https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
              size_type: xs
        fulfillments:
          - id: F8
            type: PASS
            customer:
              person:
                creds:
                  - type: PAN
                  - type: AADHAR
                  - type: DL
                  - type: VOTER_ID
            stops:
              - type: START
                location:
                  descriptor:
                    code: 'std:011'
                  gps: '28.666576, 77.233332'
                id: '1'
            vehicle:
              category: BUS
              variant: NON_AC
          - id: F9
            type: PASS
            customer:
              person:
                creds:
                  - type: PAN
                  - type: AADHAR
                  - type: DL
                  - type: VOTER_ID
            stops:
              - type: START
                location:
                  descriptor:
                    code: 'std:011'
                  gps: '28.666576, 77.233332'
                id: '1'
            vehicle:
              category: BUS
              variant: AC
          - id: FT9
            type: TICKET
            stops:
              - authorization:
                  type: QR_AND_VEHICLE_NUMBER
          - id: FT10
            type: TICKET
            stops:
              - authorization:
                  type: QR
        items:
          - id: I1
            descriptor:
              name: Single Journey Ticket
              code: SJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            time:
              label: Validity
              duration: PT2D
              timestamp: '2021-03-23T11:01:40.065Z'
          - id: I2
            descriptor:
              name: Special Fair Single Journey Ticket
              code: SFSJT
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
          - id: I7
            descriptor:
              name: Daily Pass
              code: PASS
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F8
            price:
              currency: INR
              value: '50'
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P1D
          - id: I8
            descriptor:
              name: Weekly Pass
              code: PASS
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F9
            price:
              currency: INR
              value: '100'
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P7D
          - id: I9
            descriptor:
              name: Monthly Pass
              code: PASS
              images:
                - url: >-
                    https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F9
            price:
              currency: INR
              value: '200'
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P1M
        payments:
          - collected_by: BAP
            tags:
              - descriptor:
                  code: BUYER_FINDER_FEES
                display: false
                list:
                  - descriptor:
                      code: BUYER_FINDER_FEES_PERCENTAGE
                    value: '1'
              - descriptor:
                  code: SETTLEMENT_TERMS
                display: false
                list:
                  - descriptor:
                      code: SETTLEMENT_WINDOW
                    value: PT30D
                  - descriptor:
                      code: SETTLEMENT_BASIS
                    value: INVOICE_RECEIPT
                  - descriptor:
                      code: MANDATORY_ARBITRATION
                    value: 'TRUE'
                  - descriptor:
                      code: COURT_JURISDICTION
                    value: New Delhi
                  - descriptor:
                      code: STATIC_TERMS
                    value: 'https://api.transit-solutions.com/booking/terms'
    tags:
      - descriptor:
          code: PAGINATION
          name: Pagination
        display: true
        list:
          - descriptor:
              code: PAGINATION_ID
            value: P1
          - descriptor:
              code: MAX_PAGE_NUMBER
            value: '3'
