catalog:
  descriptor:
    name: ABC Insurance Ltd
  providers:
    - id: P1
      descriptor:
        name: ABC Insurance Ltd.
        short_desc: ABC Insurance Ltd. India
        long_desc: ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc
        images:
          - url: https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png
            size_type: xs
      categories:
        - id: C1
          descriptor:
            name: Micro Insurance
            code: MICRO_INSURANCE
        - id: C2
          parent_category_id: C1
          descriptor:
            name: Micro Accidental Insurance
            code: MICRO_ACCIDENTAL_INSURANCE
      items:
        - id: I1
          category_ids:
            - C2
          descriptor:
            name: Micro Accidental Insurance
            short_desc: ABC Individual Insurance Class
          time:
            duration: P1Y
            label: TENURE
        - id: CHILD_ITEM_ID_I1
          parent_item_id: I1
          category_ids:
            - C2
          descriptor:
            name: Micro Accidental Insurance Plan
            short_desc: Individual Insurance Class
          price:
            currency: INR
            value: "900"
          tags:
            - descriptor:
                name: General Information
                code: GENERAL_INFO
              list:
                - descriptor:
                    code: ACCIDENTAL_DEATH_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: PERMANENT_TOTAL_DISABILITY_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: PERMANENT_PARTIAL_DISABILITY_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: TEMPORARY_TOTAL_DISABILITY_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: MEDICAL_EXPENSES_COVERAGE
                  value: "100000"
                - descriptor:
                    code: HOSPITALIZATION_BENEFITS
                  value: "10000"
                - descriptor:
                    code: EMI_DURING_TEMPORARY_DISABILITY
                  value: "true"
                - descriptor:
                    code: EMI_DURING_PERMANENT_DISABILITY
                  value: "false"
                - descriptor:
                    code: NUMBER_OF_EMI_PAYABLE
                  value: "5"
                - descriptor:
                    code: INITIAL_WAITING_PERIOD
                  value: "true"
                - descriptor:
                    code: MINIMUM_AGE_LIMIT
                  value: "15"
                - descriptor:
                    code: MAXIMUM_AGE_LIMIT
                  value: "75"
                - descriptor:
                    code: TNC_LINK
                  value: https://fis.test.bpp.io/tnc.html
                - descriptor:
                    code: TENURE_TYPE
                  value: TRANSIT
                - descriptor:
                    code: BASE_PRICE
                    name: Base Price
                    short_desc: Base Price
                  value: "900"
                - descriptor:
                    code: CONVIENCE_FEE
                    name: Convience Fee
                    short_desc: Convience Fee
                  value: "50"
                - descriptor:
                    code: PROCESSING_FEE
                    name: Processing Fee
                    short_desc: Processing Fee
                  value: "10"
                - descriptor:
                    code: TAX
                    name: Tax
                    short_desc: Tax
                  value: "40"
                - descriptor:
                    code: OFFER_VALIDITY
                    name: Offer validity
                    short_desc: Describes the offer validity
                  value: P15D
            - descriptor:
                name: Inclusions
                code: INCLUSIONS
              list:
                - descriptor:
                    name: Hospitalization
                - descriptor:
                    name: Surgery
            - descriptor:
                name: Exclusions
                code: EXCLUSIONS
              list:
                - descriptor:
                    name: Physiotherapy
          time:
            duration: P1Y
            label: TENURE
        - id: CHILD_ITEM_ID_I2
          parent_item_id: I1
          category_ids:
            - C2
          descriptor:
            name: Micro Accidental Insurance Plus Plan
            short_desc: Single Accidental Insurance
          price:
            currency: INR
            value: "1000"
          tags:
            - descriptor:
                name: General Information
                code: GENERAL_INFO
              list:
                - descriptor:
                    code: ACCIDENTAL_DEATH_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: PERMANENT_TOTAL_DISABILITY_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: PERMANENT_PARTIAL_DISABILITY_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: TEMPORARY_TOTAL_DISABILITY_SUM_INSURED
                  value: "10000000"
                - descriptor:
                    code: MEDICAL_EXPENSES_COVERAGE
                  value: "100000"
                - descriptor:
                    code: HOSPITALIZATION_BENEFITS
                  value: "10000"
                - descriptor:
                    code: EMI_DURING_TEMPORARY_DISABILITY
                  value: "true"
                - descriptor:
                    code: EMI_DURING_PERMANENT_DISABILITY
                  value: "false"
                - descriptor:
                    code: NUMBER_OF_EMI_PAYABLE
                  value: "5"
                - descriptor:
                    code: INITIAL_WAITING_PERIOD
                  value: "true"
                - descriptor:
                    code: MINIMUM_AGE_LIMIT
                  value: "15"
                - descriptor:
                    code: MAXIMUM_AGE_LIMIT
                  value: "75"
                - descriptor:
                    code: TNC_LINK
                  value: https://fis.test.bpp.io/tnc.html
                - descriptor:
                    code: TENURE_TYPE
                  value: TRANSIT
                - descriptor:
                    code: BASE_PRICE
                    name: Base Price
                    short_desc: Base Price
                  value: "1000"
                - descriptor:
                    code: CONVIENCE_FEE
                    name: Convience Fee
                    short_desc: Convience Fee
                  value: "50"
                - descriptor:
                    code: PROCESSING_FEE
                    name: Processing Fee
                    short_desc: Processing Fee
                  value: "10"
                - descriptor:
                    code: TAX
                    name: Tax
                    short_desc: Tax
                  value: "40"
                - descriptor:
                    code: OFFER_VALIDITY
                    name: Offer validity
                    short_desc: Describes the offer validity
                  value: P15D
            - descriptor:
                name: Inclusions
                code: INCLUSIONS
              list:
                - descriptor:
                    name: Hospitalization
                - descriptor:
                    name: Surgery
            - descriptor:
                name: Exclusions
                code: EXCLUSIONS
              list:
                - descriptor:
                    name: Physiotherapy
          time:
            duration: P1Y
            label: TENURE
      tags:
        - descriptor:
            code: MASTER_POLICY
          list:
            - descriptor:
                code: POLICY_ID
              value: e103b4a5-10f8-42c7-b888-dbf0e2edd696
      payments:
        - collected_by: BPP
  tags:
    - descriptor:
        code: BPP_TERMS
        name: BPP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bpp.com/booking/terms
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
