session_data:
  transaction_id: null
  message_id: null
  last_action: null
  mock_type: null
  city_code: null
  bap_id: null
  bap_uri: null
  bpp_id: null
  bpp_uri: null
  start_code: null
  end_code: null
  buyer_app_fee: null
  vehicle_type: null
  fulfillments: []
  category_ids: []
  provider_id: null
  fulfillment_ids: []
  item_ids: []
  items: []
  selected_items: []
  selected_item_ids: []
  billing: {}
  payments: []
  updated_payments: []
  order_id: null
  status: null
  error_code: null
  error_message: null
  quote: null
  ref_id: null
  ttl: null
  usecaseId: null
  collected_by: null
  price: null
  payment_id: null
  created_at: null
  update_fulfillment: []
  buyer_side_fulfillment_ids: []
  user_inputs: null
  first_form_testing: []
