saveData:
  - path: "$.context.transaction_id"
    key: "transaction_id"
  - path: "$.context.message_id"
    key: "message_id"
  - path: "$.message.order_id"
    key: "order_id"
  - path: "$.message.update_target"
    key: "update_target" 