save-data:
  message_id: "$.context.message_id"
  selected_item_ids: "$.message.order.items[*].id"
  selected_items: "$.message.order.items[*]"
  buyer_side_fulfillment_ids: "$.message.order.fulfillments[*]"
