order:
  fulfillments:
    - id: F1
      type: POLICY
      tags:
        - descriptor:
            code: NOMINEE_DETAILS
            name: Nominee Details
          display: false
          list:
            - descriptor:
                code: NOMINEE_NAME
              value: "Mr. | Steve | Wick | Adams"
            - descriptor:
                code: NOMINEE_DOB
              value: "17/12/2001"
            - descriptor:
                code: NOMINEE_RELATIONSHIP
              value: Child
            - descriptor:
                code: APPOINTEE_NAME
              value: "Mr. | John | Doe | Adams"
            - descriptor:
                code: APPOINTEE_RELATIONSHIP
              value: Father
            - descriptor:
                code: GOOD_HEALTH_DECLARATION
              value: Yes

  items:
    - id: CHILD_ITEM_ID_I1
      parent_item_id: I1

  provider:
    id: P1

  payments:
    - collected_by: BPP
      status: NOT-PAID
      type: ON-ORDER

  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: STATIC_TERMS
          value: "https://api.example-bap.com/booking/terms"
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
