save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  order_status: "$.message.order.status"
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  payments: "$.message.order.payments[*]"
  created_at: "$.message.order.created_at"
  updated_at: "$.message.order.updated_at"
