name: Deploy merged Service

on:
  workflow_dispatch:
  push:
    # paths:
    #   - "api-service/**"
    #   - "mock-service/**"
    branches:
      - "draft-*"
      - "release-*"

jobs:
  build-and-verify:
    runs-on: self-hosted
    environment: ${{ github.ref_name }}  # environment exactly matches branch name

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Detect build type
        run: |
          if [[ "${GITHUB_REF_NAME}" == draft* ]]; then
            echo "BUILD_TYPE=draft" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == release* ]]; then
            echo "BUILD_TYPE=release" >> $GITHUB_ENV
          else
            echo "BUILD_TYPE=default" >> $GITHUB_ENV
          fi
          echo "Detected BUILD_TYPE=$BUILD_TYPE"
          echo "Detected BUILD_TYPE=${{ steps.set_build_type.outputs.build_type }}"